// User Types
const REGISTER = "REGISTER";

const LOGIN = "LOGIN";

const LOGOUT = "LOGOUT";

const CHANGE_EMAIL = "CHANGE_EMAIL";

const CHANGE_PASSWORD = "CHANGE_PASSWORD";

const DELETE_ACCOUNT = "DELETE_ACCOUNT";


// Contact Types
const ADD_CONTACT = "ADD_CONTACT";

const UPDATE_CONTACT = "UPDATE_CONTACT";

const DELETE_CONTACT = "DELETE_CONTACT";

export default {
  REGISTER,
  LOGIN,
  LOGOUT,
  CHANGE_EMAIL,
  CHANGE_PASSWORD,
  DELETE_ACCOUNT,
  ADD_CONTACT,
  UPDATE_CONTACT,
  DELETE_CONTACT
};